version: "3.3"

services:
  mariadb:
    image: lscr.io/linuxserver/mariadb:latest #
    container_name: mariadb
    environment:
      - PUID=501
      - PGID=20
      - MYSQL_ROOT_PASSWORD=password
      - TZ=Europe/London
    volumes:
      - ./.db:/config
    ports:
      - "5306:3306"
    restart: always

  baseball:
    build:
      context: ..
      dockerfile: ../Dockerfile
    image: baseball
    environment:
      PORT: "8080"
    restart: on-failure
    volumes:
      - "./baseball.sql:/app/baseball.sql"
